stop running tests on any failure

diff --git a/test b/test
--- a/test
+++ b/test
@@ -1,5 +1,8 @@
 #!/usr/bin/env zsh
 
+# If there are any failures, stop running subsequent tests
+set -e
+
 if [ $1 = "all" ]; then
     for chapter in $(find . -name 'ch*' -type d); do
         echo $chapter
